// ===== 00_config.js =====

// Gilda Map Builder MVP 0.4
// Blocco: 00_config.js
// Configurazione globale, preset VTT, asset base, stato progetto, riferimenti DOM e utility minime.

const STORAGE_KEY = "gildaMapBuilderProject07hb";
const CHANNEL_NAME = "gildaMapBuilderChannel07h";
const isPlayerWindow = new URLSearchParams(window.location.search).get("player") === "1";
const syncChannel = ("BroadcastChannel" in window) ? new BroadcastChannel(CHANNEL_NAME) : null;

const MAP_PRESETS = {
  "room": { name:"Stanza", squaresW:30, squaresH:20, zoom:50 },
  "small_lair": { name:"Tana piccola", squaresW:50, squaresH:30, zoom:35 },
  "medium_dungeon": { name:"Dungeon medio", squaresW:80, squaresH:50, zoom:20 },
  "large_dungeon": { name:"Dungeon grande", squaresW:120, squaresH:80, zoom:15 },
  "mega_structure": { name:"Mega struttura", squaresW:200, squaresH:120, zoom:8 },
  "custom": { name:"Personalizzata", squaresW:80, squaresH:50, zoom:20 }
};

const TV_VIEWPORT = {
  name: "TV 50 pollici 4K orizzontale",
  squaresW: 38.4,
  squaresH: 21.6
};

const DEFAULT_LAYER_DEFS = [
  { id:"sfondo", name:"Sfondo", visibleMaster:true, visiblePlayer:true, locked:true },
  { id:"pavimenti", name:"Pavimenti", visibleMaster:true, visiblePlayer:true, locked:true },
  { id:"architettura", name:"Architettura", visibleMaster:true, visiblePlayer:true, locked:true },
  { id:"porte", name:"Porte e passaggi", visibleMaster:true, visiblePlayer:true, locked:false },
  { id:"arredi", name:"Arredi", visibleMaster:true, visiblePlayer:true, locked:false },
  { id:"interattivi", name:"Oggetti interattivi", visibleMaster:true, visiblePlayer:true, locked:false },
  { id:"trappole", name:"Trappole", visibleMaster:true, visiblePlayer:false, locked:false },
  { id:"token", name:"Token / Creature", visibleMaster:true, visiblePlayer:true, locked:false },
  { id:"effetti", name:"Effetti", visibleMaster:true, visiblePlayer:true, locked:false },
  { id:"nebbia", name:"Nebbia / Oscurità", visibleMaster:true, visiblePlayer:true, locked:false },
  { id:"note_master", name:"Note Master", visibleMaster:true, visiblePlayer:false, locked:false }
];

const LAYERS = DEFAULT_LAYER_DEFS.map(l => l.id);

const ASSETS = [
  { id:"stone_floor", name:"Pavimento 1×1", cat:"Base", src:"assets/base/stone_floor_seamless.svg", cellsW:1, cellsH:1, drawMode:"rect" },
  { id:"rough_wall", name:"Roccia 1×0.5", cat:"Muri", src:"assets/muri/rough_wall.svg", cellsW:1, cellsH:0.5, drawMode:"line", drawThickness:0.5 },
  { id:"old_wall", name:"Muratura 1×0.5", cat:"Muri", src:"assets/muri/old_wall.svg", cellsW:1, cellsH:0.5, drawMode:"line", drawThickness:0.5 },
  { id:"wood_door", name:"Porta 1×0.25", cat:"Porte", src:"assets/porte/wood_door_clean.svg", cellsW:1, cellsH:0.25 },
  { id:"secret_door", name:"Porta segreta 1×0.25", cat:"Porte", src:"assets/porte/secret_door_clean.svg", cellsW:1, cellsH:0.25 },
  { id:"stairs_down", name:"Scala 1×1", cat:"Scale e botole", src:"assets/scale_botole/stairs_down_clean.svg", cellsW:1, cellsH:1 },
  { id:"hatch", name:"Botola 0.5×0.5", cat:"Scale e botole", src:"assets/scale_botole/hatch_clean.svg", cellsW:0.5, cellsH:0.5 },
  { id:"crate", name:"Cassa 0.5×0.5", cat:"Oggetti", src:"assets/oggetti/crate_clean.svg", cellsW:0.5, cellsH:0.5 },
  { id:"table", name:"Tavolo 1.5×1", cat:"Oggetti", src:"assets/oggetti/table.svg", cellsW:1.5, cellsH:1 },
  { id:"fog", name:"Oscurità 3×2", cat:"Overlay", src:"assets/overlay/fog.svg", cellsW:3, cellsH:2 },
  { id:"token", name:"Token 1×1", cat:"Token", src:"assets/token/token.svg", cellsW:1, cellsH:1 },
  { id:"marker_a1", name:"A1", cat:"Icone", src:"assets/icone/marker_a1.svg", cellsW:0.5, cellsH:0.5 },
  { id:"marker_a2", name:"A2", cat:"Icone", src:"assets/icone/marker_a2.svg", cellsW:0.5, cellsH:0.5 },
  { id:"sigil", name:"Sigillo 1×1", cat:"Icone", src:"assets/icone/sigil.svg", cellsW:1, cellsH:1 }
];

let project = {
  "name": "Gilda Map Builder - Esempio Layer",
  "activeMapId": "sample_dungeon",
  "mode": "editor",
  "showGrid": true,
  "snap": true,
  "snapDivisor": 1,
  "gridSize": 100,
  "mapPreset": "room",
  "showViewport": true,
  "playerFollowEditor": true,
  "playerZoom": 100,
  "customAssets": [],
  "layers": {
    "sfondo": {
      "id": "sfondo",
      "name": "Sfondo",
      "visibleMaster": true,
      "visiblePlayer": true,
      "locked": true
    },
    "pavimenti": {
      "id": "pavimenti",
      "name": "Pavimenti",
      "visibleMaster": true,
      "visiblePlayer": true,
      "locked": true
    },
    "architettura": {
      "id": "architettura",
      "name": "Architettura",
      "visibleMaster": true,
      "visiblePlayer": true,
      "locked": true
    },
    "porte": {
      "id": "porte",
      "name": "Porte e passaggi",
      "visibleMaster": true,
      "visiblePlayer": true,
      "locked": false
    },
    "arredi": {
      "id": "arredi",
      "name": "Arredi",
      "visibleMaster": true,
      "visiblePlayer": true,
      "locked": false
    },
    "interattivi": {
      "id": "interattivi",
      "name": "Oggetti interattivi",
      "visibleMaster": true,
      "visiblePlayer": true,
      "locked": false
    },
    "trappole": {
      "id": "trappole",
      "name": "Trappole",
      "visibleMaster": true,
      "visiblePlayer": false,
      "locked": false
    },
    "token": {
      "id": "token",
      "name": "Token / Creature",
      "visibleMaster": true,
      "visiblePlayer": true,
      "locked": false
    },
    "effetti": {
      "id": "effetti",
      "name": "Effetti",
      "visibleMaster": true,
      "visiblePlayer": true,
      "locked": false
    },
    "nebbia": {
      "id": "nebbia",
      "name": "Nebbia / Oscurità",
      "visibleMaster": true,
      "visiblePlayer": true,
      "locked": false
    },
    "note_master": {
      "id": "note_master",
      "name": "Note Master",
      "visibleMaster": true,
      "visiblePlayer": false,
      "locked": false
    }
  },
  "ui": {
    "leftCollapsed": false,
    "rightCollapsed": false,
    "assetCollapsed": {}
  },
  "maps": [
    {
      "id": "sample_dungeon",
      "name": "Esempio - piccolo dungeon",
      "width": 3000,
      "height": 2000,
      "squaresW": 30,
      "squaresH": 20,
      "viewportX": 0,
      "viewportY": 0,
      "views": [],
      "groups": {},
      "playerView": {
        "x": 0,
        "y": 0,
        "w": 3000,
        "h": 2000
      },
      "objects": [
        {
          "id": "sample_001",
          "assetId": "stone_floor",
          "name": "Pavimento sala d'ingresso",
          "x": 200,
          "y": 200,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_002",
          "assetId": "stone_floor",
          "name": "Pavimento sala d'ingresso",
          "x": 200,
          "y": 400,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_003",
          "assetId": "stone_floor",
          "name": "Pavimento sala d'ingresso",
          "x": 200,
          "y": 600,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_004",
          "assetId": "stone_floor",
          "name": "Pavimento sala d'ingresso",
          "x": 400,
          "y": 200,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_005",
          "assetId": "stone_floor",
          "name": "Pavimento sala d'ingresso",
          "x": 400,
          "y": 400,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_006",
          "assetId": "stone_floor",
          "name": "Pavimento sala d'ingresso",
          "x": 400,
          "y": 600,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_007",
          "assetId": "stone_floor",
          "name": "Pavimento sala d'ingresso",
          "x": 600,
          "y": 200,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_008",
          "assetId": "stone_floor",
          "name": "Pavimento sala d'ingresso",
          "x": 600,
          "y": 400,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_009",
          "assetId": "stone_floor",
          "name": "Pavimento sala d'ingresso",
          "x": 600,
          "y": 600,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_010",
          "assetId": "stone_floor",
          "name": "Pavimento sala d'ingresso",
          "x": 800,
          "y": 200,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_011",
          "assetId": "stone_floor",
          "name": "Pavimento sala d'ingresso",
          "x": 800,
          "y": 400,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_012",
          "assetId": "stone_floor",
          "name": "Pavimento sala d'ingresso",
          "x": 800,
          "y": 600,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_013",
          "assetId": "stone_floor",
          "name": "Pavimento archivio",
          "x": 1400,
          "y": 200,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_014",
          "assetId": "stone_floor",
          "name": "Pavimento archivio",
          "x": 1400,
          "y": 400,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_015",
          "assetId": "stone_floor",
          "name": "Pavimento archivio",
          "x": 1400,
          "y": 600,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_016",
          "assetId": "stone_floor",
          "name": "Pavimento archivio",
          "x": 1600,
          "y": 200,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_017",
          "assetId": "stone_floor",
          "name": "Pavimento archivio",
          "x": 1600,
          "y": 400,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_018",
          "assetId": "stone_floor",
          "name": "Pavimento archivio",
          "x": 1600,
          "y": 600,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_019",
          "assetId": "stone_floor",
          "name": "Pavimento archivio",
          "x": 1800,
          "y": 200,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_020",
          "assetId": "stone_floor",
          "name": "Pavimento archivio",
          "x": 1800,
          "y": 400,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_021",
          "assetId": "stone_floor",
          "name": "Pavimento archivio",
          "x": 1800,
          "y": 600,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_022",
          "assetId": "stone_floor",
          "name": "Pavimento archivio",
          "x": 2000,
          "y": 200,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_023",
          "assetId": "stone_floor",
          "name": "Pavimento archivio",
          "x": 2000,
          "y": 400,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_024",
          "assetId": "stone_floor",
          "name": "Pavimento archivio",
          "x": 2000,
          "y": 600,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_025",
          "assetId": "stone_floor",
          "name": "Pavimento archivio",
          "x": 2200,
          "y": 200,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_026",
          "assetId": "stone_floor",
          "name": "Pavimento archivio",
          "x": 2200,
          "y": 400,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_027",
          "assetId": "stone_floor",
          "name": "Pavimento archivio",
          "x": 2200,
          "y": 600,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_028",
          "assetId": "stone_floor",
          "name": "Pavimento archivio",
          "x": 2400,
          "y": 200,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_029",
          "assetId": "stone_floor",
          "name": "Pavimento archivio",
          "x": 2400,
          "y": 400,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_030",
          "assetId": "stone_floor",
          "name": "Pavimento archivio",
          "x": 2400,
          "y": 600,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_031",
          "assetId": "stone_floor",
          "name": "Pavimento cripta",
          "x": 800,
          "y": 1200,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_032",
          "assetId": "stone_floor",
          "name": "Pavimento cripta",
          "x": 800,
          "y": 1400,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_033",
          "assetId": "stone_floor",
          "name": "Pavimento cripta",
          "x": 800,
          "y": 1600,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_034",
          "assetId": "stone_floor",
          "name": "Pavimento cripta",
          "x": 1000,
          "y": 1200,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_035",
          "assetId": "stone_floor",
          "name": "Pavimento cripta",
          "x": 1000,
          "y": 1400,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_036",
          "assetId": "stone_floor",
          "name": "Pavimento cripta",
          "x": 1000,
          "y": 1600,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_037",
          "assetId": "stone_floor",
          "name": "Pavimento cripta",
          "x": 1200,
          "y": 1200,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_038",
          "assetId": "stone_floor",
          "name": "Pavimento cripta",
          "x": 1200,
          "y": 1400,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_039",
          "assetId": "stone_floor",
          "name": "Pavimento cripta",
          "x": 1200,
          "y": 1600,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_040",
          "assetId": "stone_floor",
          "name": "Pavimento cripta",
          "x": 1400,
          "y": 1200,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_041",
          "assetId": "stone_floor",
          "name": "Pavimento cripta",
          "x": 1400,
          "y": 1400,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_042",
          "assetId": "stone_floor",
          "name": "Pavimento cripta",
          "x": 1400,
          "y": 1600,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_043",
          "assetId": "stone_floor",
          "name": "Pavimento cripta",
          "x": 1600,
          "y": 1200,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_044",
          "assetId": "stone_floor",
          "name": "Pavimento cripta",
          "x": 1600,
          "y": 1400,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_045",
          "assetId": "stone_floor",
          "name": "Pavimento cripta",
          "x": 1600,
          "y": 1600,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_046",
          "assetId": "stone_floor",
          "name": "Pavimento cripta",
          "x": 1800,
          "y": 1200,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_047",
          "assetId": "stone_floor",
          "name": "Pavimento cripta",
          "x": 1800,
          "y": 1400,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_048",
          "assetId": "stone_floor",
          "name": "Pavimento cripta",
          "x": 1800,
          "y": 1600,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_049",
          "assetId": "stone_floor",
          "name": "Pavimento cripta",
          "x": 2000,
          "y": 1200,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_050",
          "assetId": "stone_floor",
          "name": "Pavimento cripta",
          "x": 2000,
          "y": 1400,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_051",
          "assetId": "stone_floor",
          "name": "Pavimento cripta",
          "x": 2000,
          "y": 1600,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_052",
          "assetId": "stone_floor",
          "name": "Corridoio centrale",
          "x": 1000,
          "y": 400,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_053",
          "assetId": "stone_floor",
          "name": "Corridoio centrale",
          "x": 1200,
          "y": 400,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_054",
          "assetId": "stone_floor",
          "name": "Corridoio discendente",
          "x": 1400,
          "y": 800,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_055",
          "assetId": "stone_floor",
          "name": "Corridoio discendente",
          "x": 1400,
          "y": 1000,
          "w": 200,
          "h": 200,
          "cellsW": 2,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "pavimenti",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 200
        },
        {
          "id": "sample_056",
          "assetId": "old_wall",
          "name": "Muro sala ingresso nord",
          "x": 150,
          "y": 150,
          "w": 300,
          "h": 50,
          "cellsW": 3,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_057",
          "assetId": "old_wall",
          "name": "Muro sala ingresso nord",
          "x": 450,
          "y": 150,
          "w": 300,
          "h": 50,
          "cellsW": 3,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_058",
          "assetId": "old_wall",
          "name": "Muro sala ingresso nord",
          "x": 750,
          "y": 150,
          "w": 300,
          "h": 50,
          "cellsW": 3,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_059",
          "assetId": "old_wall",
          "name": "Muro sala ingresso nord",
          "x": 1050,
          "y": 150,
          "w": 100,
          "h": 50,
          "cellsW": 1,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_060",
          "assetId": "old_wall",
          "name": "Muro sala ingresso sud",
          "x": 150,
          "y": 800,
          "w": 300,
          "h": 50,
          "cellsW": 3,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_061",
          "assetId": "old_wall",
          "name": "Muro sala ingresso sud",
          "x": 450,
          "y": 800,
          "w": 300,
          "h": 50,
          "cellsW": 3,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_062",
          "assetId": "old_wall",
          "name": "Muro sala ingresso sud",
          "x": 750,
          "y": 800,
          "w": 300,
          "h": 50,
          "cellsW": 3,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_063",
          "assetId": "old_wall",
          "name": "Muro sala ingresso ovest",
          "x": 150,
          "y": 200,
          "w": 50,
          "h": 300,
          "cellsW": 0.5,
          "cellsH": 3,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_064",
          "assetId": "old_wall",
          "name": "Muro sala ingresso ovest",
          "x": 150,
          "y": 500,
          "w": 50,
          "h": 300,
          "cellsW": 0.5,
          "cellsH": 3,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_065",
          "assetId": "old_wall",
          "name": "Muro sala ingresso est",
          "x": 1100,
          "y": 200,
          "w": 50,
          "h": 250,
          "cellsW": 0.5,
          "cellsH": 2.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_066",
          "assetId": "old_wall",
          "name": "Muro sala ingresso est",
          "x": 1100,
          "y": 600,
          "w": 50,
          "h": 200,
          "cellsW": 0.5,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_067",
          "assetId": "old_wall",
          "name": "Muro archivio nord",
          "x": 1350,
          "y": 150,
          "w": 300,
          "h": 50,
          "cellsW": 3,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_068",
          "assetId": "old_wall",
          "name": "Muro archivio nord",
          "x": 1650,
          "y": 150,
          "w": 300,
          "h": 50,
          "cellsW": 3,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_069",
          "assetId": "old_wall",
          "name": "Muro archivio nord",
          "x": 1950,
          "y": 150,
          "w": 300,
          "h": 50,
          "cellsW": 3,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_070",
          "assetId": "old_wall",
          "name": "Muro archivio nord",
          "x": 2250,
          "y": 150,
          "w": 300,
          "h": 50,
          "cellsW": 3,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_071",
          "assetId": "old_wall",
          "name": "Muro archivio nord",
          "x": 2550,
          "y": 150,
          "w": 100,
          "h": 50,
          "cellsW": 1,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_072",
          "assetId": "old_wall",
          "name": "Muro archivio sud",
          "x": 1350,
          "y": 800,
          "w": 300,
          "h": 50,
          "cellsW": 3,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_073",
          "assetId": "old_wall",
          "name": "Muro archivio sud",
          "x": 1650,
          "y": 800,
          "w": 300,
          "h": 50,
          "cellsW": 3,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_074",
          "assetId": "old_wall",
          "name": "Muro archivio sud",
          "x": 1950,
          "y": 800,
          "w": 300,
          "h": 50,
          "cellsW": 3,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_075",
          "assetId": "old_wall",
          "name": "Muro archivio sud",
          "x": 2250,
          "y": 800,
          "w": 300,
          "h": 50,
          "cellsW": 3,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_076",
          "assetId": "old_wall",
          "name": "Muro archivio sud",
          "x": 2550,
          "y": 800,
          "w": 100,
          "h": 50,
          "cellsW": 1,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_077",
          "assetId": "old_wall",
          "name": "Muro archivio ovest",
          "x": 1350,
          "y": 200,
          "w": 50,
          "h": 250,
          "cellsW": 0.5,
          "cellsH": 2.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_078",
          "assetId": "old_wall",
          "name": "Muro archivio ovest",
          "x": 1350,
          "y": 600,
          "w": 50,
          "h": 200,
          "cellsW": 0.5,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_079",
          "assetId": "old_wall",
          "name": "Muro archivio est",
          "x": 2650,
          "y": 200,
          "w": 50,
          "h": 300,
          "cellsW": 0.5,
          "cellsH": 3,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_080",
          "assetId": "old_wall",
          "name": "Muro archivio est",
          "x": 2650,
          "y": 500,
          "w": 50,
          "h": 300,
          "cellsW": 0.5,
          "cellsH": 3,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_081",
          "assetId": "old_wall",
          "name": "Muro cripta nord",
          "x": 750,
          "y": 1150,
          "w": 300,
          "h": 50,
          "cellsW": 3,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_082",
          "assetId": "old_wall",
          "name": "Muro cripta nord",
          "x": 1050,
          "y": 1150,
          "w": 300,
          "h": 50,
          "cellsW": 3,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_083",
          "assetId": "old_wall",
          "name": "Muro cripta nord",
          "x": 1350,
          "y": 1150,
          "w": 300,
          "h": 50,
          "cellsW": 3,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_084",
          "assetId": "old_wall",
          "name": "Muro cripta nord",
          "x": 1650,
          "y": 1150,
          "w": 300,
          "h": 50,
          "cellsW": 3,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_085",
          "assetId": "old_wall",
          "name": "Muro cripta nord",
          "x": 1950,
          "y": 1150,
          "w": 300,
          "h": 50,
          "cellsW": 3,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_086",
          "assetId": "old_wall",
          "name": "Muro cripta sud",
          "x": 750,
          "y": 1800,
          "w": 300,
          "h": 50,
          "cellsW": 3,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_087",
          "assetId": "old_wall",
          "name": "Muro cripta sud",
          "x": 1050,
          "y": 1800,
          "w": 300,
          "h": 50,
          "cellsW": 3,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_088",
          "assetId": "old_wall",
          "name": "Muro cripta sud",
          "x": 1350,
          "y": 1800,
          "w": 300,
          "h": 50,
          "cellsW": 3,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_089",
          "assetId": "old_wall",
          "name": "Muro cripta sud",
          "x": 1650,
          "y": 1800,
          "w": 300,
          "h": 50,
          "cellsW": 3,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_090",
          "assetId": "old_wall",
          "name": "Muro cripta sud",
          "x": 1950,
          "y": 1800,
          "w": 300,
          "h": 50,
          "cellsW": 3,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_091",
          "assetId": "old_wall",
          "name": "Muro cripta ovest",
          "x": 750,
          "y": 1200,
          "w": 50,
          "h": 300,
          "cellsW": 0.5,
          "cellsH": 3,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_092",
          "assetId": "old_wall",
          "name": "Muro cripta ovest",
          "x": 750,
          "y": 1500,
          "w": 50,
          "h": 300,
          "cellsW": 0.5,
          "cellsH": 3,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_093",
          "assetId": "old_wall",
          "name": "Muro cripta est",
          "x": 2250,
          "y": 1200,
          "w": 50,
          "h": 300,
          "cellsW": 0.5,
          "cellsH": 3,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_094",
          "assetId": "old_wall",
          "name": "Muro cripta est",
          "x": 2250,
          "y": 1500,
          "w": 50,
          "h": 300,
          "cellsW": 0.5,
          "cellsH": 3,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_095",
          "assetId": "old_wall",
          "name": "Muro corridoio nord",
          "x": 1050,
          "y": 350,
          "w": 300,
          "h": 50,
          "cellsW": 3,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_096",
          "assetId": "old_wall",
          "name": "Muro corridoio sud",
          "x": 1050,
          "y": 650,
          "w": 300,
          "h": 50,
          "cellsW": 3,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_097",
          "assetId": "old_wall",
          "name": "Muro corridoio basso ovest",
          "x": 1350,
          "y": 800,
          "w": 50,
          "h": 300,
          "cellsW": 0.5,
          "cellsH": 3,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_098",
          "assetId": "old_wall",
          "name": "Muro corridoio basso ovest",
          "x": 1350,
          "y": 1100,
          "w": 50,
          "h": 100,
          "cellsW": 0.5,
          "cellsH": 1,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_099",
          "assetId": "old_wall",
          "name": "Muro corridoio basso est",
          "x": 1600,
          "y": 800,
          "w": 50,
          "h": 300,
          "cellsW": 0.5,
          "cellsH": 3,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_100",
          "assetId": "old_wall",
          "name": "Muro corridoio basso est",
          "x": 1600,
          "y": 1100,
          "w": 50,
          "h": 100,
          "cellsW": 0.5,
          "cellsH": 1,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "architettura",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 300
        },
        {
          "id": "sample_101",
          "assetId": "wood_door",
          "name": "Porta tra ingresso e corridoio",
          "x": 1080,
          "y": 490,
          "w": 25,
          "h": 100,
          "cellsW": 0.25,
          "cellsH": 1,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "porte",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 400
        },
        {
          "id": "sample_102",
          "assetId": "wood_door",
          "name": "Porta dell'archivio",
          "x": 1330,
          "y": 490,
          "w": 25,
          "h": 100,
          "cellsW": 0.25,
          "cellsH": 1,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "porte",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 400
        },
        {
          "id": "sample_103",
          "assetId": "wood_door",
          "name": "Porta della cripta",
          "x": 1400,
          "y": 1130,
          "w": 100,
          "h": 25,
          "cellsW": 1,
          "cellsH": 0.25,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "porte",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 400
        },
        {
          "id": "sample_104",
          "assetId": "secret_door",
          "name": "Passaggio segreto dietro gli scaffali",
          "x": 2300,
          "y": 780,
          "w": 100,
          "h": 25,
          "cellsW": 1,
          "cellsH": 0.25,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "porte",
          "visibleMaster": true,
          "visiblePlayer": false,
          "z": 400
        },
        {
          "id": "sample_105",
          "assetId": "table",
          "name": "Tavolo delle mappe",
          "x": 450,
          "y": 450,
          "w": 150,
          "h": 100,
          "cellsW": 1.5,
          "cellsH": 1,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "arredi",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 500
        },
        {
          "id": "sample_106",
          "assetId": "crate",
          "name": "Cassa",
          "x": 800,
          "y": 650,
          "w": 50,
          "h": 50,
          "cellsW": 0.5,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "arredi",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 500
        },
        {
          "id": "sample_107",
          "assetId": "crate",
          "name": "Cassa",
          "x": 870,
          "y": 650,
          "w": 50,
          "h": 50,
          "cellsW": 0.5,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "arredi",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 500
        },
        {
          "id": "sample_108",
          "assetId": "table",
          "name": "Banco archivio",
          "x": 1800,
          "y": 420,
          "w": 150,
          "h": 100,
          "cellsW": 1.5,
          "cellsH": 1,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "arredi",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 500
        },
        {
          "id": "sample_109",
          "assetId": "stairs_down",
          "name": "Scala verso il livello inferiore",
          "x": 2000,
          "y": 1500,
          "w": 100,
          "h": 100,
          "cellsW": 1,
          "cellsH": 1,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "interattivi",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 600
        },
        {
          "id": "sample_110",
          "assetId": "hatch",
          "name": "Botola nascosta",
          "x": 900,
          "y": 1300,
          "w": 50,
          "h": 50,
          "cellsW": 0.5,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "interattivi",
          "visibleMaster": true,
          "visiblePlayer": false,
          "z": 600
        },
        {
          "id": "sample_111",
          "assetId": "sigil",
          "name": "Trappola del Nodo Spezzato",
          "x": 1200,
          "y": 500,
          "w": 100,
          "h": 100,
          "cellsW": 1,
          "cellsH": 1,
          "rot": 0,
          "rotation": 0,
          "opacity": 0.8,
          "layer": "trappole",
          "visibleMaster": true,
          "visiblePlayer": false,
          "z": 700
        },
        {
          "id": "sample_112",
          "assetId": "fog",
          "name": "Zona non rivelata",
          "x": 2000,
          "y": 1200,
          "w": 300,
          "h": 200,
          "cellsW": 3,
          "cellsH": 2,
          "rot": 0,
          "rotation": 0,
          "opacity": 0.55,
          "layer": "nebbia",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 1000
        },
        {
          "id": "sample_113",
          "assetId": "token",
          "name": "Token Thiefir prova",
          "x": 300,
          "y": 300,
          "w": 100,
          "h": 100,
          "cellsW": 1,
          "cellsH": 1,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "token",
          "visibleMaster": true,
          "visiblePlayer": true,
          "z": 800
        },
        {
          "id": "sample_114",
          "assetId": "token",
          "name": "Guardia della Gilda",
          "x": 1800,
          "y": 600,
          "w": 100,
          "h": 100,
          "cellsW": 1,
          "cellsH": 1,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "token",
          "visibleMaster": true,
          "visiblePlayer": false,
          "z": 800
        },
        {
          "id": "sample_115",
          "assetId": "marker_a1",
          "name": "Nota Master A1 - accesso falso",
          "x": 200,
          "y": 100,
          "w": 50,
          "h": 50,
          "cellsW": 0.5,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "note_master",
          "visibleMaster": true,
          "visiblePlayer": false,
          "z": 1100
        },
        {
          "id": "sample_116",
          "assetId": "marker_a2",
          "name": "Nota Master A2 - leva nascosta",
          "x": 2300,
          "y": 700,
          "w": 50,
          "h": 50,
          "cellsW": 0.5,
          "cellsH": 0.5,
          "rot": 0,
          "rotation": 0,
          "opacity": 1,
          "layer": "note_master",
          "visibleMaster": true,
          "visiblePlayer": false,
          "z": 1100
        }
      ]
    }
  ]
};

function cleanDefaultProjectCanvas() {
  project.name = "Gilda Map Builder - Nuova mappa";
  project.activeMapId = "blank_dungeon";
  project.mode = "editor";
  project.showGrid = true;
  project.snap = true;
  project.snapDivisor = 1;
  project.gridSize = 100;
  project.mapPreset = "room";
  project.showViewport = true;
  project.customAssets = [];
  project.maps = [{
    id:"blank_dungeon",
    name:"Nuova mappa vuota",
    width:3000,
    height:2000,
    squaresW:30,
    squaresH:20,
    viewportX:0,
    viewportY:0,
    views:[],
    groups:{},
    smartLayers:[],
    playerView:{
      x:0,
      y:0,
      w:3000,
      h:2000
    },
    objects:[]
  }];
}

cleanDefaultProjectCanvas();

let selectedId = null;
let selectedIds = [];
let selectedAssetId = null;
let brushDrawState = null;
let smartBrushKind = "dungeon";
let smartBrushPreset = "inhabited";
let smartToolMode = null;
let smartDragState = null;
let clipboard = null;
let dragState = null;
let panState = null;
let viewportDragState = null;
let lastSyncedRaw = "";

const canvas = document.getElementById("canvas");
const canvasStage = document.getElementById("canvasStage");
const canvasWrap = document.getElementById("canvasWrap");
const smartLayer = document.getElementById("smartLayer");
const viewportLayer = document.getElementById("viewportLayer");
const viewportHandle = document.getElementById("viewportHandle");
const playerViewLayer = document.getElementById("playerViewLayer");
const brushPreview = document.getElementById("brushPreview");
const brushPreviewImg = document.getElementById("brushPreviewImg");
const statusEl = document.getElementById("status");

function activeMap() { return project.maps.find(m => m.id === project.activeMapId); }
function uid() { return "obj_" + Math.random().toString(36).slice(2,10); }
function allAssets() { return ASSETS.concat(project.customAssets || []); }
function assetById(id) { return allAssets().find(a => a.id === id); }
function status(msg) { if (statusEl) statusEl.textContent = msg; }
function grid() { return Number(project.gridSize || 120); }
function snapStep() { return grid() / Number(project.snapDivisor || 1); }
function pxFromCells(cells) { return Math.max(1, Math.round(cells * grid())); }
function cellsFromPx(px) { return +(px / grid()).toFixed(2); }
function snapValue(v) { return project.snap ? Math.round(v / snapStep()) * snapStep() : Math.round(v); }
